
server:
  port: 8083


spring:
  application:
    name: service-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
    url: jdbc:mysql://localhost:3306/commerce?useUnicode=true&characterEncoding=utf-8
    username: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
mybatis:
  config-locations: classpath:mybatis/confg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.jk.model



  instance:
    ##EurekaClient \u5411\u6CE8\u518C\u4E2D\u5FC3\u53D1\u9001\u5FC3\u8DF3\u7684\u65F6\u95F4\u95F4\u9694\uFF0C\uFF08\u5355\u4F4D\uFF1A\u79D2\uFF09\u5BA2\u6237\u7AEF\u544A\u8BC9\u6CE8\u518C\u670D\u52A1\u7AEF\u81EA\u5DF1\u4F1A\u6309\u7167\u8BE5\u89C4\u5219\u53D1\u9001\u5FC3\u8DF3
    lease-renewal-interval-in-seconds: 1
    ##EurekaServer\u5728\u6536\u5230\u6700\u540E\u4E00\u6B21\u5FC3\u8DF3\u540E\u7B49\u5F85\u7684\u65F6\u95F4\u4E0A\u9650\uFF0C\uFF08\u5355\u4F4D\uFF1A\u79D2\uFF09\uFF0C\u8D85\u8FC7\u5219\u5254\u9664\u3002\u5BA2\u6237\u7AEF\u544A\u8BC9\u6CE8\u518C\u670D\u52A1\u7AEF\u81EA\u5DF1\u4F1A\u6309\u7167\u8BE5\u89C4\u5219\u53D1\u9001\u5FC3\u8DF3
    lease-expiration-duration-in-seconds: 2